---
# Clojure configuration deployment (installation handled by preset)

- name: Make sure .lein folder is present
  file:
    path: ~/.lein
    state: directory
  tags: [clojure, config]

- name: Make sure .clojure folder is present
  file:
    path: ~/.clojure
    state: directory
  tags: [clojure, config]

- name: Make sure .m2 folder is present
  file:
    path: ~/.m2
    state: directory
  tags: [clojure, config]

- name: Make sure deps.edn is present
  template:
    src: ./templates/deps.edn
    dest: ~/.clojure/deps.edn
  tags: [clojure, config]

- name: Make sure rebel_readline.edn present
  template:
    src: ./templates/rebel_readline.edn
    dest: ~/.clojure/rebel_readline.edn
  tags: [clojure, config]

- name: Make sure settings.xml present
  template:
    src: ./templates/settings.xml
    dest: ~/.m2/settings.xml
  tags: [clojure, config]
